server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  #      读写分离配置
#  shardingsphere:
#    datasource:
#      names: master,slave
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.13.10:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#          username: root
#          password: root
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.13.11:3306/reggie?characterEncoding=utf-8
#          username: root
#          password: root
#    masterslave:
      #读写分离配置
#      load-balance-algorithm-type: round_robin #轮询
#      name: dataSource
#      master-data-source-name: master
#      slave-data-source-names: slave
#
#    props:
#        sql:
#          show: true #开启sql显示，默认false

  # 配置了main Bean容器允许覆盖bean定义。
  main:
    allow-bean-definition-overriding: true


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tGRuLpiigepDD1FyEyC
    accessKeySecret: f6yXEDMDjhFzidvnHFumGo7XW33SPz
    bucketName: ikumzxw



reggie:
  path: D:\

  #redis
redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0

cache:
  redis:
    time-to-live: 1800000 #设置缓存过期时间

